chore: add some notes on chapter 3 of working the command line
The-Mycelium-Network/bookclub pull request #17
Opened 2022-09-25 16:02 UTC by schalkneethling

Adds some notes for chapter 3 of working the command line.

fix #16

2022-09-25 22:22 UTC, KobayashiComputing commented
I have reviewed the proposed addition, and generally I think it's great. Two comments, however:

1. In the text regarding the pipe character, I recommend that the word "damn" be replaced with something like "extremely" or "astonishingly" or something similar. I think that there are many people who are still somewhat offended by "damn," even though most simply overlook it. 
2. In the "less cheatsheet," in the first line, I think that changing "up and down cursor" to "up and down arrow keys." I think this will avoid any confusion as to which keys to use.

2022-09-25 23:20 UTC, KobayashiComputing requested changes

2022-09-25 23:20 UTC, KobayashiComputing commented on working-the-command-line/chapter3/index.md
> +> The pipe is a magic and integral part of the command line. It’s super powerful and damn useful. What it does is take the output from the first command (on the left side) and “pipe” it to the second
Replace the word "damn" with something less potentially objectionable, such as "extremely" or "extraordinarily."

2022-09-25 23:20 UTC, KobayashiComputing commented on working-the-command-line/chapter3/index.md
> +- move up and down using the up and down cursor
```suggestion
- move up and down using the up and down arrow keys
```

2022-09-26 23:45 UTC, schalkneethling commented on working-the-command-line/chapter3/index.md
> +> The pipe is a magic and integral part of the command line. It’s super powerful and damn useful. What it does is take the output from the first command (on the left side) and “pipe” it to the second
Ah, yes, good point. That is a direct quote from the book, but I reckon we can clean it up. Thank you for the thoughtful suggestion.

2022-09-26 23:46 UTC, schalkneethling commented on working-the-command-line/chapter3/index.md
> +> The pipe is a magic and integral part of the command line. It’s super powerful and damn useful. What it does is take the output from the first command (on the left side) and “pipe” it to the second
```suggestion
> The pipe is a magic and integral part of the command line. It’s super powerful and extremely useful. What it does is take the output from the first command (on the left side) and “pipe” it to the second command (on the right side).
```

2022-09-26 23:47 UTC, schalkneethling commented
Thank you for your thorough review, @KobayashiComputing. This one is ready for a re-review. Thank you!

2022-09-27 03:20 UTC, KobayashiComputing approved these changes
Looks good.

2022-09-27 03:20 UTC, merged