add more details to the book README
The-Mycelium-Network/bookclub pull request #6
Opened 2022-09-12 07:42 UTC by bpires

- [x] Add about the book
- [x] Add about the author
- [x] Add about the sponsor
- [x] Include a list of participants
- [x] Include visual aids
- [x] Create a banner
- [x] Keep it light-hearted and fun

Fixes #5

2022-09-13 19:43 UTC, schalkneethling requested changes
Thank you so much for taking the time to put this together @bpires 🎉 A couple of notes and suggestions.

2022-09-13 19:43 UTC, schalkneethling commented on working-the-command-line/README.md
> +<br>
Do we _need_ these `br` tags?

2022-09-13 19:43 UTC, schalkneethling commented on working-the-command-line/README.md
> +</div>
I reckon we can download these images and add them directly to the repository. It feels a little safer. For one thing, we can be sure the image will always render. The other thing is, someone might switch up the image on us :) Also, if we do not _need_ the HTML, I generally prefer to keep the Markdown to just Markdown. It allows us to, for example, add a linter without having to mess too much with formatting rules and exceptions.

2022-09-13 19:43 UTC, schalkneethling commented on working-the-command-line/README.md
> +
Same here as my previous comment

2022-09-13 19:43 UTC, schalkneethling commented on working-the-command-line/README.md
> +<br/>
Ditto :)

2022-09-13 19:43 UTC, schalkneethling commented on working-the-command-line/README.md
> +</div>
Ditto

2022-09-13 19:43 UTC, schalkneethling commented on working-the-command-line/README.md
> +
Again here, perhaps better to add the images directly to the repo.

2022-09-14 02:48 UTC, bpires commented on working-the-command-line/README.md
> +<br>
Fair point!

2022-09-14 03:13 UTC, bpires commented on working-the-command-line/README.md
> +</div>
Thanks for pointing this out! It feels safer, indeed. And on that note, I think it's best to reduce the number of images to the minimum. I should have given this more thought 😅
In relation to HTML, I couldn't find a way to reduce the image and align it without recurring to the <img> tag. Please let me know if I'm missing something

2022-09-14 04:19 UTC, bpires commented
Thanks for the review @schalkneethling 🍄 I did some changes and remodelled the README based on your suggestions. I also included the latest changes in a new section. Please let me know what you think about it!

2022-09-18 17:51 UTC, schalkneethling commented
@bpires Do you have the source image you used for the header? Also, a link to the person’s Etsy store. Thanks!

2022-09-18 20:20 UTC, bpires commented
@schalkneethling it's https://www.etsy.com/shop/AshElizabethArt
And the image https://i.etsystatic.com/15228211/r/il/368ea9/2967627473/il_794xN.2967627473_tgil.jpg

2022-09-20 20:30 UTC, schalkneethling commented
@bpires what about something like this for the header template:
https://design.penpot.app/#/view/c74f9c80-3778-11ed-a5c2-cf2300df1f4f?page-id=c74f9c81-3778-11ed-a5c2-cf2300df1f4f&section=interactions&index=0&share-id=08802d90-3923-11ed-a5c2-cf2300df1f4f

2022-09-20 23:57 UTC, bpires commented
Loved the header @schalkneethling! Just two things:
1. There seems to be an issue with the font weight on the "network" word of the TMN logo
2. You may consider including the author of the book (like "Working the Command Line, by Remy Sharp").

Anyway, LGTM! :)

2022-09-21 16:48 UTC, schalkneethling commented
> [Something like this](https://www.canva.com/design/DAFM0MvHEBI/O9BnAMFD0aG0EW-fSv1cNA/edit?utm_content=DAFM0MvHEBI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) (Don't know how to use penpot yet, just a draft on Canvas to illustrate).

I really like that! I will update the one on PenPot.

2022-09-25 16:04 UTC, schalkneethling commented
@bpires This looks great! We just need to update the header graphic. Thanks!

2022-09-26 19:44 UTC, bpires commented
@schalkneethling, I've updated the banner and added links to the individual notes and resources of each chapter. I think we're good to go.

PS: The existent content regarding chapter 4 will be moved to the appropriate markdown file under chapter4 folder.

2022-09-27 00:00 UTC, schalkneethling requested changes
Just two more items, almost there 🙌 - Thanks so much, @bpires, I cannot wait for this one to land.

2022-09-27 01:36 UTC, bpires commented on working-the-command-line/README.md
> +![Bookclub banner](./assets/bookclub-banner.png)
Good to know, thanks!

2022-09-28 01:04 UTC, schalkneethling commented on working-the-command-line/README.md
> +![Bookclub banner](assets/bookclub-banner.png)
@bpires I think these will work once we merge the PR. IF not, we can figure out why it does not then.

2022-09-28 03:33 UTC, bpires commented
I've accepted the suggestions and resized the image, leaving all in markdown with no HTML. 🎉 

PS: I'm curious: how do you preview the file output? Because it rendered fine for me here on GitHub with the `./` at the beginning of the file path. I'm asking just to be sure, I guess either way works.

2022-10-02 15:59 UTC, schalkneethling commented
> PS: I'm curious: how do you preview the file output? Because it rendered fine for me here on GitHub with the `./` at the beginning of the file path. I'm asking just to be sure, I guess either way works.

I was using "view rich diff", but it seems the "view file" option is the better one.

2022-10-02 15:59 UTC, schalkneethling approved these changes
Thank you for persisting with this one @bpires 🙌

2022-10-02 16:00 UTC, merged